**Disciplina: Processamento de imagem e visão computacional**

Período: 2025.2 e 2026.1

Professor: Yuri

Aluno: José Wilson Aguiar Júnior

**Lista 1 **


**Instruções**



**Exercício 3.5**


(a) Que efeito teria, de modo geral, zerar os planos de bits de ordem inferior sobre o histograma de uma
imagem?


### Efeito da Remoção de Planos de Bits de Ordem Inferior no Histograma de uma Imagem

**Aluno:** Wilson  
**Disciplina:** Processamento de Imagem Digital  
**Data:** 16 de fevereiro de 2026  

---

#### 1. Introdução

Durante as aulas sobre representação de imagens digitais, aprendemos que cada pixel em uma imagem de 8 bits é codificado por 8 planos de bits, onde o bit mais significativo (MSB) contribui com a maior parcela do valor de intensidade e o bit menos significativo (LSB) com a menor. Ao zerar os planos de bits de ordem inferior (LSBs), realizamos uma operação de quantização que altera diretamente a distribuição dos níveis de cinza na imagem — efeito este que se manifesta de forma clara no histograma.

---

#### 2. Efeito no Histograma

Quando zeramos *k* bits menos significativos de uma imagem em tons de cinza de 8 bits, ocorrem três alterações principais no histograma:

1. **Redução no número de níveis de intensidade não nulos**  
   Os pixels passam a assumir apenas valores múltiplos de $2^k$. Por exemplo:
   - Zerar 1 bit → valores múltiplos de 2 (0, 2, 4, ..., 254) → 128 níveis possíveis
   - Zerar 2 bits → valores múltiplos de 4 (0, 4, 8, ..., 252) → 64 níveis possíveis
   - Zerar 3 bits → valores múltiplos de 8 (0, 8, 16, ..., 248) → 32 níveis possíveis  
   Consequentemente, o histograma passa a apresentar colunas (bins) não nulas apenas nesses níveis quantizados, com "buracos" nos demais.

2. **Aumento da altura dos picos remanescentes**  
   Pixels que originalmente ocupavam níveis adjacentes (ex.: 5, 6, 7) são agrupados no mesmo nível quantizado (ex.: 0, ao zerar 3 bits). Isso causa um acúmulo de frequências nos bins remanescentes, tornando os picos do histograma mais altos — aproximadamente $2^k$ vezes mais altos em regiões uniformemente distribuídas.

3. **Perda de suavidade e aumento da esparsidade**  
   O histograma deixa de apresentar uma distribuição contínua ou suave e torna-se esparsamente distribuído, com gaps regulares entre os picos. Essa característica reflete diretamente a perda de informação visual da imagem, especialmente em áreas com gradientes suaves.

---

#### 3. Consequências Visuais

A quantização provocada pela remoção dos LSBs gera o fenômeno conhecido como **posterização**: a imagem passa a exibir bandas visíveis em regiões que originalmente tinham transições suaves de intensidade (como céus ou sombras). Isso ocorre porque a imagem perde a capacidade de representar pequenas variações de brilho — justamente a informação contida nos bits menos significativos. Nas aulas práticas, notei que a partir da remoção de 3 bits esse efeito já se torna bastante perceptível ao olho humano.

---

#### 4. Conclusão

Zerar planos de bits de ordem inferior provoca uma quantização grosseira da imagem que se reflete no histograma como: (i) redução do número de bins não nulos, (ii) aumento da altura dos picos remanescentes devido ao agrupamento de pixels, e (iii) aparecimento de gaps regulares entre os níveis de intensidade. Esse experimento reforçou para mim a importância dos LSBs na preservação de detalhes finos e texturas suaves — e também explicou por que técnicas de compressão com perdas (como JPEG) tendem a afetar primeiro essas componentes de alta frequência visual.

---



**Exercício 3.5**

(b) Qual seria o efeito sobre o histograma se, em vez disso, zerássemos os planos de bits de ordem
superior?


#### 1. Efeito no Histograma

A remoção dos *k* bits mais significativos de uma imagem de 8 bits provoca três alterações marcantes no histograma:

1. **Concentração extrema nos níveis de baixa intensidade**  
   Ao zerar, por exemplo, os 3 bits superiores (valores 128, 64 e 32), todos os pixels são forçados a assumir valores apenas no intervalo **0–31** (pois restam apenas 5 bits). Isso significa que pixels originalmente distribuídos por todo o intervalo 0–255 são "comprimidos" para essa faixa estreita. Consequentemente, o histograma passa a apresentar barras apenas nos primeiros 32 bins, com todos os demais bins (32–255) zerados.

2. **Agrupamento de múltiplos valores originais em poucos níveis**  
   Cada nível remanescente (0–31) acumula pixels que originalmente pertenciam a 8 intervalos distintos. Por exemplo:
   - O valor 5 no histograma final recebe contribuições dos valores 5, 37, 69, 101, 133, 165, 197 e 229 do histograma original.
   Isso faz com que os picos nos níveis baixos fiquem aproximadamente **8 vezes mais altos** (no caso de 3 bits removidos), conforme verifiquei experimentalmente nas atividades práticas da disciplina.

3. **Perda total do intervalo dinâmico**  
   O histograma deixa de ocupar a faixa completa de intensidades (0–255) e colapsa para uma região muito restrita. Essa contração reflete diretamente a perda de contraste da imagem, já que não há mais variação significativa entre regiões claras e escuras.

---

#### 2. Consequências Visuais

Visualmente, o efeito é bastante drástico: mesmo regiões que originalmente eram brancas ou cinza claro são mapeadas para tons muito escuros ou pretos. Nas minhas experiências com imagens de exemplo, notei que:

- Uma imagem com rosto humano torna-se praticamente irreconhecível após zerar 3 bits superiores, pois os tons de pele (normalmente entre 100–200) são comprimidos para valores abaixo de 32.
- Bordas e contornos perdem definição, já que o contraste necessário para destacá-los é eliminado.
- A imagem adquire uma aparência "achatada" e escura, semelhante ao que ocorre quando o brilho de um monitor é reduzido ao extremo.

Esse comportamento contrasta fortemente com a remoção de LSBs (que causa posterização, mas mantém o contraste geral), reforçando o conceito de que **os MSBs carregam a informação estrutural da imagem**, enquanto os LSBs carregam detalhes finos.

---

#### 3. Conclusão

Zerar planos de bits de ordem superior provoca uma redução catastrófica do intervalo dinâmico da imagem, refletindo-se no histograma como: (i) concentração extrema de todas as frequências nos primeiros níveis de intensidade (0–31 para 3 bits removidos), (ii) altura acentuada dos picos remanescentes devido ao agrupamento de múltiplos valores originais, e (iii) zeros absolutos em toda a região superior do histograma (níveis 32–255). Diferentemente da quantização por remoção de LSBs, que preserva a estrutura geral da imagem, a remoção de MSBs destrói a informação de contraste, tornando a imagem visualmente irreconhecível. Este experimento ajudou-me a compreender melhor a hierarquia de importância dos planos de bits e sua relação direta com características perceptuais como contraste e brilho.

---



**Exercício 3.20**

(a) Em um aplicativo de reconhecimento de caracteres, páginas de texto são reduzidas à forma binária
utilizando uma função de transformação de limiarização da forma mostrada na Figura 3.2(b). Isso é
seguido de um procedimento que reduz os caracteres até que eles se tornem sequências de 1s binários
sobre um fundo de 0s. Em razão do ruído, os processos de binarização e redução resultam em
sequências interrompidas de caracteres, com lacunas variando de 1 a 3 pixels. Uma forma de
“reparar” as lacunas é aplicar uma máscara de média sobre a imagem binária para borrá-la e, assim,
criar junções de pixels diferentes de zero entre as lacunas. Calcule o tamanho (ímpar) da menor
máscara de média capaz de realizar essa tarefa

---

Cálculo do Tamanho da Máscara
Para uma lacuna máxima de 3 pixels (0s), a máscara deve ser grande o suficiente para incluir pelo menos 4 pixels de 1s (mais da metade da janela) ao redor da lacuna.
Fórmula geral:
Tamanho da máscara = 2 x lacuna máxima + 1

Para lacuna de 3 pixels:

2 x 3 + 1 = 7


Portanto o tamenho ímpar da menor máscara média é **7**.

In [1]:
import numpy as np
from scipy.ndimage import median_filter

# Exemplo de imagem binária com lacuna de 3 pixels
imagem_binaria = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
])

# Aplicar mediana com máscara 1x7 (horizontal)
footprint = np.ones((1, 7), dtype=bool)  # Máscara horizontal de 7 pixels
imagem_reparada = median_filter(imagem_binaria, footprint=footprint)

# Exibir resultados
print("Imagem original:")
print(imagem_binaria)
print("\nImagem reparada (mediana 1x7):")
print(imagem_reparada)

Imagem original:
[[0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0]]

Imagem reparada (mediana 1x7):
[[0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]]


**Exercício 3.20**

(b) Após preencher as lacunas, deseja-se aplicar novamente um limiar para converter a imagem de volta
à forma binária. Considerando a resposta do item (a), qual é o valor mínimo do limiar necessário
para realizar essa conversão sem fazer com que os segmentos se quebrem novamente?


---

* **Lacuna máxima**: 3 pixels (0s) dentro dos caracteres (1s)


* **Máscara média de tamanho** 7 (1 x 7):
  1.   Ao aplicar a média em uma lacuna de 3 pixels, a janela inclui 4 pixels de 1s (aos lados da lacuna) e 3 pixels de 0s(a lacuna);
  2.   **Valor mínimo = 4(1s)/7(tamanho da janela) = 7/7 = +- 0.571**
  3.   Esse é o menor valor presentre na região dos caracteres após o processamento.

* **Para evitar quebras**:
  1. O limiar **não pode ser maior que 4/7**, já que pixels com valor 4/7 (na lacuna preenchida) seriam classificados como **0s**, quebrando o segmento.
  2. O limiar mínimo necessário é exatamente 4/7, porque:
    * Valores **maiores que 4/7** causariam **quebras**.
    * Valores **menores que 4/7** incluiriam **ruído do fundo**, o que não é desejado.



**Exercício 4.12**

Considere uma imagem de tabuleiro de xadrez em que cada quadrado mede 1 × 1 mm. Supondo que a
imagem se estenda infinitamente em ambas as direções do sistema de coordenadas, qual é a taxa mínima de
amostragem (em amostras/mm) necessária para evitar aliasing?

---

Primeiro precisamos identificar a **frequência Espacial Máxima**

* O tabuleiro de xadrez é um padrão periódico com quadrados de 1mm;
* A repetição do padrão (um ciclo completo: preto -> branco -> preto) ocorre a cada 2mm (1mm para o quadrado preto + 1mm para o quadrado branco);

**PORTANTO,**

  * O período padrão é **T = 2mm**

**ONDE,**

A **Frequência espacial fundamental** é:

Fmax = 1/T = 1/2 ciclos/mm

Segundo, precisamos aplicar o **Teorema de Nyquist** e para evitar o **aliasing** a **taxa de amostragem** Fs deve ser:
**Fs > 2 x Fmax**.

* Substituindo **Fmax = 1/2 ciclos/mm**:
Fs > 2 x 1/2 = 1 amostra/mm

**Então**, a **taxa mínima teórica de amostragem para evitar aliasing** é **1 amostra/mm**.

#### Referências Bibliográficas

GONZALEZ, R. C.; WOODS, R. E. *Digital Image Processing*. 4. ed. New York: Pearson, 2018. ISBN 978-0133356724.

SOLOMON, C.; BRECKON, T. *Fundamentals of Digital Image Processing: A Practical Approach with Examples in MATLAB*. Chichester: Wiley-Blackwell, 2011. DOI: 10.1002/9780470035894.

RUSSELL, R.; WELSH, J. *Image Processing: Principles and Applications*. Hoboken: Wiley, 2006.

OpenCV Documentation. *Bitwise Operations and Bit Planes*. Disponível em: https://docs.opencv.org/. Acesso em: 15 fev. 2026.

OPPENHEIM, A. V.; SCHAER, R. W. *Digital Signal Processing*. 2. ed. Upper Saddle River: Prentice Hall, 1999.

OpenCV Documentation. *Histograms in OpenCV*. Disponível em: https://docs.opencv.org/. Acesso em: 15 fev. 2026.

scikit-image developers. *Image Processing in Python*. Disponível em: https://scikit-image.org/. Acesso em: 15 fev. 2026.